/**
 * Style Dictionary v4 configuration — IDEM Design System
 *
 * Builds two modes (light / dark) × three formats:
 *   1. CSS custom properties  →  dist/{mode}/variables.css
 *   2. JavaScript ES6 exports →  dist/{mode}/tokens.js
 *   3. Flat JSON              →  dist/{mode}/tokens.flat.json
 *
 * Token source files use W3C DTCG format ($value / $type).
 * Style Dictionary v4 handles this natively via usesDtcg: true.
 */

import StyleDictionary from 'style-dictionary';

// ─── Custom: flat JSON format ────────────────────────────────────────────────
// Outputs { "token-name": "#hex", ... } — one entry per token, kebab-cased key.

StyleDictionary.registerFormat({
  name: 'json/flat-kebab',
  format: ({ dictionary }) => {
    const out = {};
    for (const token of dictionary.allTokens) {
      out[token.name] = token.$value ?? token.value;
    }
    return JSON.stringify(out, null, 2);
  },
});

// ─── Custom: ES6 named exports ───────────────────────────────────────────────
// Outputs one `export const camelCaseName = "#hex";` per token.

StyleDictionary.registerFormat({
  name: 'javascript/es6-named',
  format: ({ dictionary, file }) => {
    const header = `/**\n * ${file.destination}\n * Auto-generated by Style Dictionary — do not edit.\n */\n\n`;
    const exports = dictionary.allTokens
      .map(token => {
        const name = token.name
          .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()); // kebab → camelCase
        const value = token.$value ?? token.value;
        return `export const ${name} = ${JSON.stringify(value)};`;
      })
      .join('\n');
    return header + exports + '\n';
  },
});

// ─── Custom: kebab name transform that drops the `DEFAULT` sentinel ──────────
// DTCG forbids a token node from having both a $value and nested child tokens.
// Where a token needs a default value AND sub-states (e.g. `input.border` plus
// `input.border.focus`), we model the default as a `DEFAULT` child. This name
// transform strips that exact segment so `input.border.DEFAULT` still emits as
// `idem-input-border` (unchanged), while `input.border.focus` emits alongside it.
// Only the exact uppercase `DEFAULT` is stripped, so real `default` token names
// (e.g. `colour.background.default`) are untouched.

StyleDictionary.registerTransform({
  name: 'name/kebab-default',
  type: 'name',
  transform: (token, config, options) => {
    const prefix = (options && options.prefix) || (config && config.prefix) || '';
    const segs = [prefix, ...token.path.filter((p) => p !== 'DEFAULT')];
    return segs
      .join(' ')
      .replace(/([a-z0-9])([A-Z])/g, '$1 $2') // split camelCase (onBackground → on background)
      .split(/[^a-zA-Z0-9]+/)
      .filter(Boolean)
      .join('-')
      .toLowerCase();
  },
});

// ─── Shared transform group ───────────────────────────────────────────────────
// Uses SD's built-in 'css' transforms but keeps the name as kebab-case
// (DEFAULT-aware, see above).

StyleDictionary.registerTransformGroup({
  name: 'idem/css',
  transforms: ['attribute/cti', 'name/kebab-default', 'color/css'],
});

StyleDictionary.registerTransformGroup({
  name: 'idem/json',
  transforms: ['attribute/cti', 'name/kebab-default', 'color/css'],
});

// ─── Build helper ────────────────────────────────────────────────────────────

async function buildMode(mode) {
  const sd = new StyleDictionary({
    usesDtcg: true,

    source: [`tokens/tokens.${mode}.json`],

    platforms: {

      // 1. CSS custom properties
      css: {
        transformGroup: 'idem/css',
        prefix: 'idem',
        buildPath: `dist/${mode}/`,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables',
            options: {
              selector: mode === 'light' ? ':root' : ':root[data-theme="dark"], .dark',
              outputReferences: false,
            },
          },
        ],
      },

      // 2. JavaScript ES6 named exports
      js: {
        transformGroup: 'idem/json',
        prefix: 'idem',
        buildPath: `dist/${mode}/`,
        files: [
          {
            destination: 'tokens.js',
            format: 'javascript/es6-named',
          },
        ],
      },

      // 3. Flat JSON  { "idem-colour-background-default": "#ffffff", ... }
      json: {
        transformGroup: 'idem/json',
        prefix: 'idem',
        buildPath: `dist/${mode}/`,
        files: [
          {
            destination: 'tokens.flat.json',
            format: 'json/flat-kebab',
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
}

// ─── Run ─────────────────────────────────────────────────────────────────────

await buildMode('light');
await buildMode('dark');

console.log('\n✓ Style Dictionary build complete.');
console.log('  dist/light/variables.css');
console.log('  dist/light/tokens.js');
console.log('  dist/light/tokens.flat.json');
console.log('  dist/dark/variables.css');
console.log('  dist/dark/tokens.js');
console.log('  dist/dark/tokens.flat.json');
