/**
 * Style Dictionary v4 configuration — token pipeline (client-agnostic)
 *
 * Builds two modes (light / dark) × three formats:
 *   1. CSS custom properties  →  dist/{mode}/variables.css
 *   2. JavaScript ES6 exports →  dist/{mode}/tokens.js
 *   3. Flat JSON              →  dist/{mode}/tokens.flat.json
 *
 * Token source files use W3C DTCG format ($value / $type).
 * Style Dictionary v4 handles this natively via usesDtcg: true.
 */

import StyleDictionary from 'style-dictionary';
import config from './pipeline.config.mjs';

// Per-client token name prefix. Sourced from pipeline.config.mjs, with an
// optional TOKEN_PREFIX env override for one-off builds.
const PREFIX = process.env.TOKEN_PREFIX ?? config.prefix;

// ─── Custom: flat JSON format ────────────────────────────────────────────────
// Outputs { "token-name": "#hex", ... } — one entry per token, kebab-cased key.

StyleDictionary.registerFormat({
  name: 'json/flat-kebab',
  format: ({ dictionary }) => {
    const out = {};
    for (const token of dictionary.allTokens) {
      out[token.name] = token.$value ?? token.value;
    }
    return JSON.stringify(out, null, 2);
  },
});

// ─── Custom: ES6 named exports ───────────────────────────────────────────────
// Outputs one `export const camelCaseName = "#hex";` per token.

StyleDictionary.registerFormat({
  name: 'javascript/es6-named',
  format: ({ dictionary, file }) => {
    const header = `/**\n * ${file.destination}\n * Auto-generated by Style Dictionary — do not edit.\n */\n\n`;
    const exports = dictionary.allTokens
      .map(token => {
        const name = token.name
          .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()); // kebab → camelCase
        const value = token.$value ?? token.value;
        return `export const ${name} = ${JSON.stringify(value)};`;
      })
      .join('\n');
    return header + exports + '\n';
  },
});

// ─── Shared transform group ───────────────────────────────────────────────────
// One group for all three platforms: kebab-cased names (prefix-aware, camelCase
// split — `colour.onBackground.brand` → `<prefix>-colour-on-background-brand`)
// and CSS-formatted colours (8-digit hex → rgba()).
//
// Token names that are ALSO group prefixes (e.g. `input.border` alongside
// `input.border.focus`) are not modelled here: the Figma sync rejects that shape
// outright — see setDeep() in scripts/lib/figma-to-dtcg.mjs — because Style
// Dictionary would silently drop one of the two. Fix it by renaming in Figma.

StyleDictionary.registerTransformGroup({
  name: 'tokens/kebab',
  transforms: ['attribute/cti', 'name/kebab', 'color/css'],
});

// ─── Build helper ────────────────────────────────────────────────────────────

async function buildMode(mode) {
  const sd = new StyleDictionary({
    usesDtcg: true,

    source: [`tokens/tokens.${mode}.json`],

    platforms: {

      // 1. CSS custom properties
      css: {
        transformGroup: 'tokens/kebab',
        prefix: PREFIX,
        buildPath: `dist/${mode}/`,
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables',
            options: {
              selector: mode === 'light' ? ':root' : ':root[data-theme="dark"], .dark',
              outputReferences: false,
            },
          },
        ],
      },

      // 2. JavaScript ES6 named exports
      js: {
        transformGroup: 'tokens/kebab',
        prefix: PREFIX,
        buildPath: `dist/${mode}/`,
        files: [
          {
            destination: 'tokens.js',
            format: 'javascript/es6-named',
          },
        ],
      },

      // 3. Flat JSON  { "<prefix>-colour-background-default": "#ffffff", ... }
      json: {
        transformGroup: 'tokens/kebab',
        prefix: PREFIX,
        buildPath: `dist/${mode}/`,
        files: [
          {
            destination: 'tokens.flat.json',
            format: 'json/flat-kebab',
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
}

// ─── Run ─────────────────────────────────────────────────────────────────────

await buildMode('light');
await buildMode('dark');

console.log('\n✓ Style Dictionary build complete.');
console.log('  dist/light/variables.css');
console.log('  dist/light/tokens.js');
console.log('  dist/light/tokens.flat.json');
console.log('  dist/dark/variables.css');
console.log('  dist/dark/tokens.js');
console.log('  dist/dark/tokens.flat.json');
